#!/bin/bash

declare -a ids=(
    "0-LZmbcAAAAJ"
    "U4i0WGsAAAAJ"
    "qenoZwUAAAAJ"
    "W8l_RCwAAAAJ"
    "arrutJcAAAAJ"
    "-c9whrAAAAAJ"
    "3HbeiywAAAAJ"
    "OhVWhdYAAAAJ"
    "sX0ZypwAAAAJ"
    "w3kGtMIAAAAJ"
    "MPFzJQgAAAAJ"
    "j0AZtowAAAAJ"
    "Z4LHkiIAAAAJ"
    "zMTnSe8AAAAJ"
    "TNI8FOoAAAAJ"
    "a5GDhcsAAAAJ"
    "1pwyaYgAAAAJ"
    "6dfA060AAAAJ"
    "y7weYdYAAAAJ"
    "sOq9t-AAAAAJ"
    "ejJVE0wAAAAJ"
    "RiZ-RdwAAAAJ"
    "hlthz-YAAAAJ"
    "nw-Vv3oAAAAJ"
    "5z1S51MAAAAJ"
    "XZtcvyEAAAAJ"
    "2Dd5uoIAAAAJ"
    "TJEUdh4AAAAJ"
    "SR5fXbYAAAAJ"
    "4kETHY4AAAAJ"
    "UZuKOMQAAAAJ"
    "Cg9yFBQAAAAJ"
    "dGSPY_0AAAAJ"
    "T7ZMcGkAAAAJ"
    "XxBWSgoAAAAJ"
    "WxZ_6nsAAAAJ"
    "Eo6JfS8AAAAJ"
    "2VgRQOEAAAAJ"
    "VOj7M1gAAAAJ"
    "g7c_OQMAAAAJ"
    "oEifmSgAAAAJ"
    "qwC3vG8AAAAJ"
    "u6OFo3YAAAAJ"
    "eQQpTi8AAAAJ"
    "JXtOJyAAAAAJ"
    "W4JVsUoAAAAJ"
    "CL7jAd8AAAAJ"
    "bLz-hogAAAAJ"
    "Nds56VgAAAAJ"
    "WADV6B4AAAAJ"
    "RzVG0dkAAAAJ"
    "Oo4ElF4AAAAJ"
    "bh4v5sAAAAAJ"
    "isdiwE8AAAAJ"
    "by8C-jMAAAAJ"
    "gyfMndoAAAAJ"
    "07tNFdgAAAAJ"
)

for id in "${ids[@]}"
do
   python main.py --add_scholar_id $id
done

